#!/usr/bin/env python3
"""Write and validate the machine-readable data-readiness state."""

from __future__ import annotations

import argparse
from datetime import datetime
import hashlib
import json
import os
from pathlib import Path
from typing import Any


DATA_READINESS_PATH = Path("results/derived/data-readiness.json")
VALID_STATUSES = {"pending_review", "analysis_ready"}


class DataReadinessError(ValueError):
    """Raised when the data-readiness contract is incomplete or stale."""


def _project_path(
    value: str | Path,
    field: str,
    *,
    root: Path,
    must_exist: bool,
) -> tuple[str, Path]:
    raw = str(value).strip().replace("\\", "/")
    candidate = Path(raw)
    if not raw or candidate.is_absolute() or ".." in candidate.parts:
        raise DataReadinessError(f"{field} must be a non-empty project-relative path")
    target = (root / candidate).resolve(strict=False)
    try:
        relative = target.relative_to(root).as_posix()
    except ValueError as error:
        raise DataReadinessError(f"{field} escapes the project") from error
    if must_exist and not target.is_file():
        raise DataReadinessError(f"{field} does not exist: {relative}")
    return relative, target


def _hash(path: Path, algorithm: str) -> str:
    digest = hashlib.new(algorithm)
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def write_data_readiness(
    *,
    status: str,
    authoritative_input: str | Path,
    input_format: str,
    input_locator: str,
    unresolved_issues: int,
    producer: str | Path,
    decision_source: str | Path | None = None,
    run_id: str | None = None,
    state_path: str | Path = DATA_READINESS_PATH,
    root: str | Path = ".",
) -> Path:
    project = Path(root).resolve(strict=True)
    if status not in VALID_STATUSES:
        raise DataReadinessError(f"unsupported status: {status}")
    if isinstance(unresolved_issues, bool) or not isinstance(unresolved_issues, int) or unresolved_issues < 0:
        raise DataReadinessError("unresolved_issues must be a non-negative integer")
    if status == "analysis_ready" and unresolved_issues:
        raise DataReadinessError("analysis_ready requires zero unresolved blocking issues")
    normalized_input, input_path = _project_path(
        authoritative_input,
        "authoritative_input",
        root=project,
        must_exist=True,
    )
    normalized_producer, _ = _project_path(
        producer,
        "producer",
        root=project,
        must_exist=True,
    )
    normalized_state, state_target = _project_path(
        state_path,
        "state_path",
        root=project,
        must_exist=False,
    )
    del normalized_state
    if not isinstance(input_format, str) or not input_format.strip():
        raise DataReadinessError("input_format must be explicit")
    if not isinstance(input_locator, str) or not input_locator.strip():
        raise DataReadinessError("input_locator must be explicit; use 'file' for a single-table file")
    if any(
        character in input_format + input_locator
        for character in ('"', "\r", "\n")
    ):
        raise DataReadinessError("input_format or input_locator contains unsupported characters")
    effective_run_id = (run_id if run_id is not None else os.getenv("EPI_RUN_ID", "")).strip()
    if status == "analysis_ready" and not effective_run_id:
        raise DataReadinessError("analysis_ready must be generated by a recorded preparation run")
    normalized_decision: str | None = None
    if decision_source is not None and str(decision_source).strip():
        normalized_decision, _ = _project_path(
            decision_source,
            "decision_source",
            root=project,
            must_exist=status == "analysis_ready",
        )
    payload = {
        "schema_version": 1,
        "status": status,
        "authoritative_input": normalized_input,
        "input_format": input_format.strip(),
        "input_locator": input_locator.strip(),
        "unresolved_issues": unresolved_issues,
        "producer": normalized_producer,
        "decision_source": normalized_decision,
        "run_id": effective_run_id,
        "hash_algorithm": "sha256",
        "input_hash": _hash(input_path, "sha256"),
        "generated_at": datetime.now().astimezone().isoformat(timespec="seconds"),
    }
    state_target.parent.mkdir(parents=True, exist_ok=True)
    temporary = state_target.with_name(f".{state_target.name}.{os.getpid()}.tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    os.replace(temporary, state_target)
    return state_target


def read_data_readiness(
    state_path: str | Path = DATA_READINESS_PATH,
    *,
    root: str | Path = ".",
) -> dict[str, Any]:
    project = Path(root).resolve(strict=True)
    _, target = _project_path(state_path, "state_path", root=project, must_exist=True)
    try:
        payload = json.loads(target.read_text(encoding="utf-8-sig"))
    except (OSError, json.JSONDecodeError) as error:
        raise DataReadinessError(f"invalid data-readiness state: {type(error).__name__}") from error
    if not isinstance(payload, dict) or payload.get("schema_version") != 1:
        raise DataReadinessError("unsupported data-readiness state version")
    return payload


def assert_data_readiness(
    state_path: str | Path = DATA_READINESS_PATH,
    *,
    root: str | Path = ".",
) -> dict[str, Any]:
    project = Path(root).resolve(strict=True)
    state = read_data_readiness(state_path, root=project)
    if state.get("status") != "analysis_ready":
        raise DataReadinessError(f"data are not analysis_ready: {state.get('status')}")
    if state.get("unresolved_issues") != 0:
        raise DataReadinessError(f"blocking issues remain: {state.get('unresolved_issues')}")
    for field in (
        "authoritative_input",
        "input_format",
        "input_locator",
        "producer",
        "run_id",
        "hash_algorithm",
        "input_hash",
    ):
        if not isinstance(state.get(field), str) or not state[field].strip():
            raise DataReadinessError(f"invalid or missing field: {field}")
    _, input_path = _project_path(
        state["authoritative_input"],
        "authoritative_input",
        root=project,
        must_exist=True,
    )
    _project_path(state["producer"], "producer", root=project, must_exist=True)
    decision_source = state.get("decision_source")
    if decision_source is not None:
        if not isinstance(decision_source, str) or not decision_source.strip():
            raise DataReadinessError("decision_source must be null or a non-empty relative path")
        _project_path(decision_source, "decision_source", root=project, must_exist=True)
    algorithm = state["hash_algorithm"]
    if algorithm not in {"md5", "sha256"}:
        raise DataReadinessError(f"unsupported hash algorithm: {algorithm}")
    if _hash(input_path, algorithm) != state["input_hash"]:
        raise DataReadinessError(f"authoritative input changed after readiness: {state['authoritative_input']}")
    current_run_id = os.getenv("EPI_RUN_ID", "").strip()
    if current_run_id and current_run_id != state["run_id"]:
        raise DataReadinessError("data readiness was not generated by the current preparation run")
    return state


def analysis_source(
    state_path: str | Path = DATA_READINESS_PATH,
    *,
    root: str | Path = ".",
) -> dict[str, str | Path]:
    state = assert_data_readiness(state_path, root=root)
    return {
        "path": Path(root).resolve(strict=True) / state["authoritative_input"],
        "format": state["input_format"],
        "locator": state["input_locator"],
    }


def analysis_input(
    state_path: str | Path = DATA_READINESS_PATH,
    *,
    root: str | Path = ".",
) -> Path:
    source = analysis_source(state_path, root=root)
    path = source["path"]
    if not isinstance(path, Path):
        raise DataReadinessError("analysis source path is invalid")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--state", type=Path, default=DATA_READINESS_PATH)
    args = parser.parse_args()
    if not args.check:
        parser.error("--check is required")
    try:
        state = assert_data_readiness(args.state)
    except (OSError, DataReadinessError) as error:
        print(f"ERROR: {error}")
        return 1
    print(f"data readiness passed: {state['authoritative_input']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
